version: '3.7'

services:
    blackrock_gunicorn:
        build:
          context: .

        volumes:
            # - .:/app/
            - staticfiles:/app/staticfiles
        
        container_name: blackrock_gunicorn
        
        ports:
            - "8000:8000"
        # env_file: 
        #     - './tsm_auth/.env'

        networks:
            - blackrock_network
        restart: always
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: blackrokinvest_db
            POSTGRES_USER: blackrokinvest
            POSTGRES_PASSWORD: Blackrokinvest@1234##

        ports:
        - "5432:5432"  # Expose the PostgreSQL port to your local machine or change as needed
        volumes:
        - pgdata:/var/lib/postgresql/data



    nginx:
        build: ./nginx
        volumes: 
            - staticfiles:/app/staticfiles
            - ./nginx/letsencrypt:/etc/letsencrypt/

        ports: 
            - "80:80"
            - "443:443"
        networks:
            - blackrock_network
        
        depends_on: 
            - blackrock_gunicorn
    
volumes:
    staticfiles:
    blackrock_authservice: 

networks:
    blackrock_network:
        driver: bridge

