version: '3.7'

services:
    blackrock_gunicorn:
        build:
          context: .

        volumes:
            # - .:/app/
            - staticfiles:/app/staticfiles
        
        container_name: blackrock_gunicorn
        
        ports:
            - "8000:8000"
        # env_file: 
        #     - './tsm_auth/.env'

        networks:
            - blackrock_network
        restart: always

        depends_on:
            - blackrokinvest_db

    
    blackrokinvest_db:
        image: postgres:latest
        restart: always
        volumes:
            - blackrokinvest_vol:/var/lib/postgresql/data
        networks:
            - blackrock_network
        container_name: blackrokinvest_db_container
        env_file: 
            - './backend/.env'
        ports:
            - 5432:5432
        
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}


    nginx:
        build: ./nginx
        volumes: 
            - staticfiles:/app/staticfiles
            - ./nginx/letsencrypt:/etc/letsencrypt/

        ports: 
            - "80:80"
            - "443:443"
        networks:
            - blackrock_network
        
        depends_on: 
            - blackrock_gunicorn
    
volumes:
    staticfiles:
    blackrock_authservice: 
    blackrokinvest_vol: 

networks:
    blackrock_network:
        driver: bridge

