version: '3.7'

services:
    blackrock_gunicorn:
        build:
          context: .

        volumes:
            # - .:/app/
            - staticfiles:/app/staticfiles
        
        container_name: blackrock_gunicorn
        
        ports:
            - "8000:8000"
        env_file: 
            - './backend/.env'

        networks:
            - blackrock_network
        restart: always

        depends_on:
            - blackrokinvest_db

    
    blackrokinvest_db:
        image: postgres:latest
        restart: always
        volumes:
            - blackrokinvest_vol:/var/lib/postgresql/data
        networks:
            - blackrock_network
        container_name: blackrokinvest_db_container
        env_file: 
            - './backend/.env'
        ports:
            - 5433:5432
        
        # command: [ "${POSTGRES_PASSWORD}" ]
        environment:
            POSTGRES_PASSWORD: blackrokinvest
            POSTGRES_USER: blackrokinvest
            POSTGRES_DB: blackrok


# DB_ENGINE="django.db.backends.postgresql_psycopg2"
# POSTGRES_PASSWORD="blackrokinvest"
# POSTGRES_USER="blackrokinvest"
# POSTGRES_DB="blackrok"
# DB_HOST="192.168.15.16"
# DB_PORT=5433


    nginx:
        build: ./nginx
        volumes: 
            - staticfiles:/app/staticfiles
            - ./nginx/letsencrypt:/etc/letsencrypt/

        ports: 
            - "81:80"
            - "443:443"
        networks:
            - blackrock_network
        
        depends_on: 
            - blackrock_gunicorn
    
volumes:
    staticfiles:
    blackrock_authservice: 
    blackrokinvest_vol: 

networks:
    blackrock_network:
        driver: bridge

