version: '3.7'

services:
    blackrock_gunicorn:
        build:
          context: .

        volumes:
            # - .:/app/
            - staticfiles:/app/staticfiles
        
        container_name: blackrock_gunicorn
        
        ports:
            - "8000:8000"
        env_file: 
            - './backend/.env'

        networks:
            - blackrock_network
        restart: always

        depends_on:
            - blackrokinvest_db


    nginx:
        build: ./nginx
        volumes: 
            - staticfiles:/app/staticfiles
            - ./nginx/letsencrypt:/etc/letsencrypt/

        ports: 
            - "81:80"
            - "443:443"
        networks:
            - blackrock_network
        
        depends_on: 
            - blackrock_gunicorn
    
volumes:
    staticfiles:
    blackrock_authservice: 
    blackrokinvest_vol: 

networks:
    blackrock_network:
        driver: bridge

