# Generated by Django 4.2.3 on 2023-07-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_payments_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('rejected', 'rejected')], default='pending', max_length=15),
        ),
    ]
