# Generated by Django 4.2.3 on 2023-07-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_payments_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_ref',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
