# Generated by Django 4.2 on 2023-07-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_wallet_accumulated_profit_wallet_today_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(choices=[('DEPOSITE', 'DEPOSITE'), ('WITHDRAWAL', 'WITHDRAWAL')], max_length=25),
        ),
    ]
