# Generated by Django 4.2.3 on 2023-07-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_payments_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
