# Generated by Django 4.2.3 on 2023-07-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledetail',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
