# Generated by Django 4.2.3 on 2023-07-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofiledetail_invite_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiledetail',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
    ]
