# Generated by Django 4.2.3 on 2023-07-20 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0005_userprofiledetail_is_invited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledetail',
            name='invited_user',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
