# Generated by Django 4.2.3 on 2023-07-22 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofiledetail_invite_code'),
        ('authentication', '0006_alter_userprofiledetail_invited_user'),
    ]

    operations = [
    ]
