# Generated by Django 4.2.3 on 2023-08-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_userprofiledetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledetail',
            name='invite_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
